-- CreateEnum
CREATE TYPE "public"."CourseType" AS ENUM ('THEORY_ONLY', 'THEORY_WITH_LAB');

-- AlterTable
ALTER TABLE "public"."Course" ADD COLUMN     "aat" DOUBLE PRECISION,
ADD COLUMN     "cie1" DOUBLE PRECISION,
ADD COLUMN     "cie2" DOUBLE PRECISION,
ADD COLUMN     "cie3" DOUBLE PRECISION,
ADD COLUMN     "courseType" "public"."CourseType" NOT NULL DEFAULT 'THEORY_ONLY',
ADD COLUMN     "lab" DOUBLE PRECISION,
ADD COLUMN     "see" DOUBLE PRECISION;
